/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js during development and kept here so
// TypeScript works before the first local dev run.
